In [16]:
import numpy as np
import cv2

img = cv2.imread('shapes2.png')
imgGrey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

#get threshold to turn img binary
_, thresh = cv2.threshold(imgGrey, 240, 255, cv2.THRESH_BINARY)
#get contours of objects
#RETR_TREE gets contour Hierarchy and stores it as explained below
#CHAIN_APPROX_NONE stores the coordinates of the contours themselves
contours, _ = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)

for contour in contours:
    print(contour)
    approx = cv2.approxPolyDP(contour, 0.01*cv2.arcLength(contour, True), True)
    print(approx[0])
    
    #[approx] in an array
    cv2.drawContours(img, [approx], 0, (0,0,0), 5)
    
    #just for the text coords
    x = approx.ravel()[0]
    y = approx.ravel()[1]
    
    
    #determine the shape by the amount of elements in approx
    if len(approx) == 3:
        cv2.putText(img, "Triangle", (x,y), cv2.FONT_HERSHEY_COMPLEX, 0.5, (0,0,0))
    elif len(approx) == 4:
        x, y, w, h = cv2.boundingRect(approx)
        aspectRatio = float(w) / h
        if 1>= aspectRatio >= 0.95:
            cv2.putText(img, "Square", (x,y), cv2.FONT_HERSHEY_COMPLEX, 0.5, (0,0,0))   
        else:    
            cv2.putText(img, "Rectangle", (x,y), cv2.FONT_HERSHEY_COMPLEX, 0.5, (0,0,0))   
    elif len(approx) == 5:
        cv2.putText(img, "Pentagon", (x,y), cv2.FONT_HERSHEY_COMPLEX, 0.5, (0,0,0)) 
    elif len(approx) == 10:
        cv2.putText(img, "Star", (x,y), cv2.FONT_HERSHEY_COMPLEX, 0.5, (0,0,0)) 
    else:
        cv2.putText(img, "Circle", (x,y), cv2.FONT_HERSHEY_COMPLEX, 0.5, (0,0,0)) 
        
        
cv2.imshow("shapes",img)
cv2.waitKey(0)
cv2.destroyAllWindows()


[[[0 0]]

 [[0 1]]

 [[0 2]]

 ...

 [[3 0]]

 [[2 0]]

 [[1 0]]]
[[0 0]]
[[[806 490]]

 [[807 489]]

 [[808 489]]

 ...

 [[805 493]]

 [[805 492]]

 [[805 491]]]
[[805 491]]
[[[563 430]]

 [[564 429]]

 [[565 429]]

 ...

 [[560 430]]

 [[561 430]]

 [[562 430]]]
[[564 429]]
[[[208 428]]

 [[209 427]]

 [[210 427]]

 ...

 [[205 430]]

 [[206 430]]

 [[207 429]]]
[[209 427]]
[[[1059   42]]

 [[1060   41]]

 [[1061   41]]

 ...

 [[1057   45]]

 [[1058   44]]

 [[1058   43]]]
[[1060   41]]
[[[37 37]]

 [[38 36]]

 [[39 36]]

 ...

 [[36 40]]

 [[36 39]]

 [[36 38]]]
[[36 38]]
[[[632  26]]

 [[633  25]]

 [[634  25]]

 ...

 [[629  26]]

 [[630  26]]

 [[631  26]]]
[[622  26]]


<img src="https://docs.opencv.org/4.x/tree_hierarchy.png" alt="contours example">


RETR_TREE EXPLAINED

Take contour-0 : It is in hierarchy-0. Next contour in same hierarchy is contour-7. No previous contours. Child is contour-1. And no parent. So array is [7,-1,1,-1].

Take contour-2 : It is in hierarchy-1. No contour in same level. No previous one. Child is contour-3. Parent is contour-1. So array is [-1,-1,3,1].

Result:
hierarchy
array([[[ 7, -1,  1, -1],
        [-1, -1,  2,  0],
        [-1, -1,  3,  1],
        [-1, -1,  4,  2],
        [-1, -1,  5,  3],
        [ 6, -1, -1,  4],
        [-1,  5, -1,  4],
        [ 8,  0, -1, -1],
        [-1,  7, -1, -1]]])
Additional Resources